### ISSUE TITLE
pch.h generates without c++ standard

### ISSUE THREAD

**Issue by drizt** [nanoant/CMakePCHCompiler#32] opened 2019-04-29 17:01 UTC
My OS Fedora 29. I create console Qt application and tri to compile it with PCH support. So console output.

```
[taurus@lix debug]$ cmake -DCMAKE_BUILD_TYPE=Debug ..
-- The CXX compiler identification is GNU 8.3.1
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/taurus/tmp/pchtest/debug
[taurus@lix debug]$ make VERBOSE=1
/usr/bin/cmake -S/home/taurus/tmp/pchtest -B/home/taurus/tmp/pchtest/debug --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/taurus/tmp/pchtest/debug/CMakeFiles /home/taurus/tmp/pchtest/debug/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/taurus/tmp/pchtest/debug'
make -f CMakeFiles/pchtest.pch_autogen.dir/build.make CMakeFiles/pchtest.pch_autogen.dir/depend
make[2]: Entering directory '/home/taurus/tmp/pchtest/debug'
cd /home/taurus/tmp/pchtest/debug && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/taurus/tmp/pchtest /home/taurus/tmp/pchtest /home/taurus/tmp/pchtest/debug /home/taurus/tmp/pchtest/debug /home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest.pch_autogen.dir/DependInfo.cmake --color=
Dependee "/home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest.pch_autogen.dir/DependInfo.cmake" is newer than depender "/home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest.pch_autogen.dir/depend.internal".
Dependee "/home/taurus/tmp/pchtest/debug/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest.pch_autogen.dir/depend.internal".
Scanning dependencies of target pchtest.pch_autogen
make[2]: Leaving directory '/home/taurus/tmp/pchtest/debug'
make -f CMakeFiles/pchtest.pch_autogen.dir/build.make CMakeFiles/pchtest.pch_autogen.dir/build
make[2]: Entering directory '/home/taurus/tmp/pchtest/debug'
[ 14%] Automatic MOC for target pchtest.pch
/usr/bin/cmake -E cmake_autogen /home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest.pch_autogen.dir/AutogenInfo.cmake Debug
AutoMoc: Generating "moc_predefs.h" because it doesn't exist
AutoMoc: Running command:
/usr/lib64/ccache/c++ -dM -E -c /usr/share/cmake/Modules/CMakeCXXCompilerABI.cpp -I/home/taurus/tmp/pchtest/debug -I/home/taurus/tmp/pchtest -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/lib64/qt5/mkspecs/linux-g++ -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include -DQT_CORE_LIB
AutoMoc: Generating MOC compilation /home/taurus/tmp/pchtest/debug/pchtest.pch_autogen/mocs_compilation.cpp
AutoGen: Writing settings file "/home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest.pch_autogen.dir/AutogenOldSettings.txt"
make[2]: Leaving directory '/home/taurus/tmp/pchtest/debug'
[ 14%] Built target pchtest.pch_autogen
make -f CMakeFiles/pchtest.pch.dir/build.make CMakeFiles/pchtest.pch.dir/depend
make[2]: Entering directory '/home/taurus/tmp/pchtest/debug'
cd /home/taurus/tmp/pchtest/debug && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/taurus/tmp/pchtest /home/taurus/tmp/pchtest /home/taurus/tmp/pchtest/debug /home/taurus/tmp/pchtest/debug /home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest.pch.dir/DependInfo.cmake --color=
Dependee "/home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest.pch.dir/DependInfo.cmake" is newer than depender "/home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest.pch.dir/depend.internal".
Dependee "/home/taurus/tmp/pchtest/debug/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest.pch.dir/depend.internal".
Scanning dependencies of target pchtest.pch
make[2]: Leaving directory '/home/taurus/tmp/pchtest/debug'
make -f CMakeFiles/pchtest.pch.dir/build.make CMakeFiles/pchtest.pch.dir/build
make[2]: Entering directory '/home/taurus/tmp/pchtest/debug'
[ 28%] Building CXX object CMakeFiles/pchtest.pch.dir/pchtest.pch_autogen/mocs_compilation.cpp.o
/usr/lib64/ccache/c++  -DQT_CORE_LIB -I/home/taurus/tmp/pchtest/debug -I/home/taurus/tmp/pchtest -I/home/taurus/tmp/pchtest/debug/pchtest.pch_autogen/include -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++  -g   -fPIC -std=gnu++11 -o CMakeFiles/pchtest.pch.dir/pchtest.pch_autogen/mocs_compilation.cpp.o -c /home/taurus/tmp/pchtest/debug/pchtest.pch_autogen/mocs_compilation.cpp
[ 42%] Building CXXPCH object CMakeFiles/pchtest.pch.dir/pch.h.gch
/usr/lib64/ccache/c++  -DQT_CORE_LIB -I/home/taurus/tmp/pchtest/debug -I/home/taurus/tmp/pchtest -I/home/taurus/tmp/pchtest/debug/pchtest.pch_autogen/include -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++  -g   -fPIC -x c++-header -o CMakeFiles/pchtest.pch.dir/pch.h.gch -c /home/taurus/tmp/pchtest/pch.h
make[2]: Leaving directory '/home/taurus/tmp/pchtest/debug'
[ 42%] Built target pchtest.pch
make -f CMakeFiles/pchtest_autogen.dir/build.make CMakeFiles/pchtest_autogen.dir/depend
make[2]: Entering directory '/home/taurus/tmp/pchtest/debug'
cd /home/taurus/tmp/pchtest/debug && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/taurus/tmp/pchtest /home/taurus/tmp/pchtest /home/taurus/tmp/pchtest/debug /home/taurus/tmp/pchtest/debug /home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest_autogen.dir/DependInfo.cmake --color=
Dependee "/home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest_autogen.dir/DependInfo.cmake" is newer than depender "/home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest_autogen.dir/depend.internal".
Dependee "/home/taurus/tmp/pchtest/debug/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest_autogen.dir/depend.internal".
Scanning dependencies of target pchtest_autogen
make[2]: Leaving directory '/home/taurus/tmp/pchtest/debug'
make -f CMakeFiles/pchtest_autogen.dir/build.make CMakeFiles/pchtest_autogen.dir/build
make[2]: Entering directory '/home/taurus/tmp/pchtest/debug'
[ 57%] Automatic MOC for target pchtest
/usr/bin/cmake -E cmake_autogen /home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest_autogen.dir/AutogenInfo.cmake Debug
AutoMoc: Generating "moc_predefs.h" because it doesn't exist
AutoMoc: Running command:
/usr/lib64/ccache/c++ -dM -E -c /usr/share/cmake/Modules/CMakeCXXCompilerABI.cpp -I/home/taurus/tmp/pchtest/debug -I/home/taurus/tmp/pchtest -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/lib64/qt5/mkspecs/linux-g++ -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include -DQT_CORE_LIB
AutoMoc: Generating MOC compilation /home/taurus/tmp/pchtest/debug/pchtest_autogen/mocs_compilation.cpp
AutoGen: Writing settings file "/home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest_autogen.dir/AutogenOldSettings.txt"
make[2]: Leaving directory '/home/taurus/tmp/pchtest/debug'
[ 57%] Built target pchtest_autogen
make -f CMakeFiles/pchtest.dir/build.make CMakeFiles/pchtest.dir/depend
make[2]: Entering directory '/home/taurus/tmp/pchtest/debug'
cd /home/taurus/tmp/pchtest/debug && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/taurus/tmp/pchtest /home/taurus/tmp/pchtest /home/taurus/tmp/pchtest/debug /home/taurus/tmp/pchtest/debug /home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest.dir/DependInfo.cmake --color=
Dependee "/home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest.dir/DependInfo.cmake" is newer than depender "/home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest.dir/depend.internal".
Dependee "/home/taurus/tmp/pchtest/debug/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest.dir/depend.internal".
Scanning dependencies of target pchtest
make[2]: Leaving directory '/home/taurus/tmp/pchtest/debug'
make -f CMakeFiles/pchtest.dir/build.make CMakeFiles/pchtest.dir/build
make[2]: Entering directory '/home/taurus/tmp/pchtest/debug'
[ 71%] Building CXX object CMakeFiles/pchtest.dir/pchtest_autogen/mocs_compilation.cpp.o
/usr/lib64/ccache/c++  -DQT_CORE_LIB -I/home/taurus/tmp/pchtest/debug -I/home/taurus/tmp/pchtest -I/home/taurus/tmp/pchtest/debug/pchtest_autogen/include -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++  -g   -include /home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest.pch.dir/pch.h -fPIC -std=gnu++11 -o CMakeFiles/pchtest.dir/pchtest_autogen/mocs_compilation.cpp.o -c /home/taurus/tmp/pchtest/debug/pchtest_autogen/mocs_compilation.cpp
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: /home/taurus/tmp/pchtest/debug/CMakeFiles/pchtest.pch.dir/pch.h: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/pchtest.dir/build.make:63: CMakeFiles/pchtest.dir/pchtest_autogen/mocs_compilation.cpp.o] Error 1
make[2]: Leaving directory '/home/taurus/tmp/pchtest/debug'
make[1]: *** [CMakeFiles/Makefile2:74: CMakeFiles/pchtest.dir/all] Error 2
make[1]: Leaving directory '/home/taurus/tmp/pchtest/debug'
make: *** [Makefile:84: all] Error 2
```

Then I tried to drop `-std=gnu++11` from latest compilation command and hit enter. And then compiled without problems.

**Comment by nanoant** [comment] 2019-04-30 21:30
@mick-p1982 Can you look also at this one, you have removed carrying over `CXX_STANDARD` to PCH target and added explicit `-std=gnu++...` in "difficult cases" 🙄 Do you remember what was the trick there?

**Comment by nanoant** [comment] 2019-05-01 13:04
Okay I have investigated this issue a bit and this looks like duplicate of #23, I will close this and keep the investigation at #23. Let move discussion there.

**Closed by nanoant** 2019-05-01 13:04 UTC
